dromara/dynamic-tp

- README.md
关联[issues](https://github.com/lyh200/dynamic-tp-spring-cloud-starter/issues/2)
> :book: 解决md文件乱码,规范md文件

- starter/starter-zookeeper/pom.xml
- starter/starter-zookeeper/src/main/java/com/dtp/starter/zookeeper/refresh/ZookeeperRefresher.java
1. 统一配置中心实现starter的加载方式 实现InitializingBean
2. 去掉commons-lang3依赖，去掉guava-16依赖
3. 代码优化
> update ZookeeperRefresher implements InitializingBean and code format

- README.md
- common/src/main/java/com/dtp/common/config/DtpProperties.java
- common/src/main/java/com/dtp/common/constant/DynamicTpConst.java
- core/pom.xml
- core/src/main/java/com/dtp/core/handler/ConfigHandler.java
- core/src/main/java/com/dtp/core/parser/AbstractConfigParser.java
- core/src/main/java/com/dtp/core/parser/ConfigParser.java
- core/src/main/java/com/dtp/core/parser/JsonConfigParser.java
- core/src/main/java/com/dtp/core/parser/PropertiesConfigParser.java
- core/src/main/java/com/dtp/core/parser/YamlConfigParser.java
- core/src/main/java/com/dtp/core/refresh/AbstractRefresher.java
- core/src/main/java/com/dtp/core/support/PropertiesBinder.java
- core/src/main/java/com/dtp/core/support/TaskQueue.java
- core/src/main/java/com/dtp/core/thread/DtpExecutor.java
- example/example-apollo/src/main/resources/dynamic-tp-apollo-demo-dtp.yml
- example/example-apollo/src/main/resources/grafana.json
- example/example-consul-cloud/src/main/resources/dynamic-tp-cloud-consul-demo-dtp.yml
- example/example-consul-cloud/src/main/resources/grafana.json
- example/example-nacos-cloud/src/main/resources/dynamic-tp-nacos-cloud-demo-dtp-dev.yml
- example/example-nacos-cloud/src/main/resources/grafana.json
- example/example-nacos/src/main/resources/dynamic-tp-nacos-demo-dtp-dev.yml
- example/example-nacos/src/main/resources/grafana.json
- example/example-zookeeper-cloud/pom.xml
- example/example-zookeeper-cloud/src/main/resources/grafana.json
- example/example-zookeeper/src/main/resources/application.yml
- example/example-zookeeper/src/main/resources/grafana.json
- pom.xml
- starter/starter-zookeeper/src/main/java/com/dtp/starter/zookeeper/autoconfigure/ZkConfigEnvironmentProcessor.java
- starter/starter-zookeeper/src/main/java/com/dtp/starter/zookeeper/refresh/ZookeeperRefresher.java
- starter/starter-zookeeper/src/main/java/com/dtp/starter/zookeeper/util/CuratorUtil.java
> mvn intsall failed

- common/src/main/java/com/dtp/common/em/CollectorTypeEnum.java
- core/src/main/java/com/dtp/core/handler/CollectorHandler.java
- core/src/main/java/com/dtp/core/monitor/collector/InternalLogCollector.java
- core/src/main/java/com/dtp/core/spring/DtpPostProcessor.java
1、#52 @DynamicTp注解修饰的Common线程池支持spring的ThreadPoolTaskExecutor
2、增加internal_logging指标手机类型，指标输出到业务系统日志文件中
> Develop my branch

- common/src/main/java/com/dtp/common/config/DtpProperties.java
- pom.xml
- starter/starter-configcenter/pom.xml
- starter/starter-configcenter/starter-etcd/pom.xml
- starter/starter-configcenter/starter-etcd/src/main/java/com/dtp/starter/etcd/autoconfigure/EtcdAutoConfiguration.java
- starter/starter-configcenter/starter-etcd/src/main/java/com/dtp/starter/etcd/autoconfigure/EtcdConfigEnvironmentProcessor.java
- starter/starter-configcenter/starter-etcd/src/main/java/com/dtp/starter/etcd/refresh/EtcdListener.java
- starter/starter-configcenter/starter-etcd/src/main/java/com/dtp/starter/etcd/refresh/EtcdRefresher.java
- starter/starter-configcenter/starter-etcd/src/main/java/com/dtp/starter/etcd/util/EtcdUtil.java
- starter/starter-configcenter/starter-etcd/src/main/resources/META-INF/spring.factories
- starter/starter-configcenter/starter-etcd/src/test/java/com/dtp/starter/etcd/util/EtcdUtilTest.java
#55 
1.支持Etcd配置中心
2.支持配置类型json和properties
两种配置类型已测试通过
> dynamic-tp支持Etcd配置中心

- checkstyle/checkstyle.xml
- pom.xml
新增maven checkstyle插件和基于阿里规约的配置
> 增加checkstyle

- docs/docs/guide/use/maven.md
> fix-modify-text

- adapter/adapter-rocketmq/src/main/java/com/dtp/adapter/rocketmq/RocketMqDtpAdapter.java
- example/example-zookeeper-cloud/pom.xml
Related issue: https://github.com/dromara/dynamic-tp/issues/147
> Add support for rockqtmq producer

- adapter/adapter-rabbitmq/pom.xml
- adapter/adapter-rabbitmq/src/main/java/com/dtp/adapter/rabbitmq/RabbitMqDtpAdapter.java
- adapter/pom.xml
- example/example-adapter/example-adapter-rabbitmq/pom.xml
- example/example-adapter/example-adapter-rabbitmq/src/main/java/com/dtp/example/RabbitMqExampleApplication.java
- example/example-adapter/example-adapter-rabbitmq/src/main/java/com/dtp/example/controller/TestController.java
- example/example-adapter/example-adapter-rabbitmq/src/main/java/com/dtp/example/mq/RabbitMqConfig.java
- example/example-adapter/example-adapter-rabbitmq/src/main/java/com/dtp/example/mq/RabbitMqConsumer.java
- example/example-adapter/example-adapter-rabbitmq/src/main/resources/application.yml
- example/example-adapter/pom.xml
- pom.xml
- starter/starter-adapter/pom.xml
- starter/starter-adapter/starter-adapter-rabbitmq/pom.xml
- starter/starter-adapter/starter-adapter-rabbitmq/src/main/java/com.dtp.starter.adapter.rabbitmq.autoconfigure/RabbitMqTpAutoConfiguration.java
- starter/starter-adapter/starter-adapter-rabbitmq/src/main/resources/META-INF/spring.factories
Related issue: https://github.com/dromara/dynamic-tp/issues/69
> Add support for rabbitmq

- common/src/main/java/com/dtp/common/constant/DynamicTpConst.java
- common/src/main/java/com/dtp/common/properties/DtpProperties.java
- core/src/main/java/com/dtp/core/spring/DtpConfigurationSelector.java
> 当组件不启用时可以通过手动配置关闭

- common/src/main/java/com/dtp/common/timer/HashedWheelTimer.java
- common/src/main/java/com/dtp/common/timer/Timeout.java
- common/src/main/java/com/dtp/common/timer/Timer.java
- common/src/main/java/com/dtp/common/timer/TimerTask.java
- example/example-adapter/example-adapter-dubbo/pom.xml
- pom.xml
- test/pom.xml
- test/test-core/src/test/java/com/dtp/test/core/thread/DtpExecutorBenchmarkTest.java
- test/test-core/src/test/java/com/dtp/test/core/thread/DtpExecutorTest.java
- test/test-core/src/test/java/com/dtp/test/core/thread/ScheduledDtpExecutorTest.java
- test/test-core/src/test/resources/dynamic-tp-demo.yml
- test/test-core/src/test/resources/dynamic-tp-nacos-demo-dtp-dev.yml
- test/test-core/src/test/resources/junit-platform.properties
1. add some dptExecutor test cases
2. move test correlation to dependencyManagement
3. fix dubbo artifactId naming error
> add some dptExecutor test cases

- test/pom.xml
> test error

- adapter/adapter-rocketmq/pom.xml
- adapter/adapter-rocketmq/src/main/java/com/dtp/adapter/rocketmq/AliyunOnsRocketMqAdapter.java
- pom.xml
- starter/starter-adapter/starter-adapter-rocketmq/pom.xml
- starter/starter-adapter/starter-adapter-rocketmq/src/main/java/com/dtp/starter/adapter/rocketmq/autoconfigure/AliyunOnsRocketMqAutoConfiguration.java
- starter/starter-adapter/starter-adapter-rocketmq/src/main/resources/META-INF/spring.factories
> RocketMQ阿里云商业版支持

- common/pom.xml
- common/src/main/java/com/dtp/common/json/parser/AbstractJsonParser.java
- common/src/main/java/com/dtp/common/json/parser/FastJsonParser.java
- common/src/main/java/com/dtp/common/json/parser/GsonParser.java
- common/src/main/java/com/dtp/common/json/parser/JacksonParser.java
- common/src/main/java/com/dtp/common/json/parser/JsonParser.java
- common/src/main/java/com/dtp/common/util/JsonUtil.java
- common/src/main/java/com/dtp/common/util/JsonUtils.java
- common/src/main/resources/META-INF/services/com.dtp.common.json.parser.JsonParser
- pom.xml
- test/test-common/pom.xml
- test/test-common/src/test/java/com/dtp/test/common/util/JsonUtilTest.java
新增JSON接口，使用Jackson/Gson/Fastjson实现，引入包设置为optional=true，根据引入dynamic-tp的项目自带序列化jar包自动选择哪一种实现，并且减少第三方包依赖
https://github.com/dromara/dynamic-tp/issues/223
> feat(添加JsonUtil代替额外引入包的JsonUtils方法 #223)

- core/src/main/java/com/dtp/core/thread/OrderedDtpExecutor.java
- test/test-core/src/test/java/com/dtp/test/core/thread/OrderedDtpExecutorTest.java
> Optimize OrderedDtpExecutor

- test/test-core/src/test/java/org/dromara/dynamictp/test/core/thread/EagerDtpExecutorTest.java
>  add eager UT

- starter/starter-common/src/main/java/org/dromara/dynamictp/starter/common/binder/SpringBootPropertiesBinder.java
> [ISSUE #307] support springboot 1.x property binding

- core/src/main/java/org/dromara/dynamictp/core/notifier/base/DingNotifier.java
> issues#314 fix DingNotifier

- example/example-polaris-cloud/src/main/resources/bootstrap.yml
- starter/starter-configcenter/cloud-starter-polaris/src/main/java/org/dromara/dynamictp/starter/cloud/polaris/refresher/CloudPolarisRefresher.java
fix: https://github.com/dromara/dynamic-tp/issues/317#issuecomment-1669240927
> fix: switch refresh-type to default in SCT in CloudPolarisRefresher

- common/src/main/java/org/dromara/dynamictp/common/entity/ThreadPoolStats.java
- core/src/main/java/org/dromara/dynamictp/core/converter/ExecutorConverter.java
- core/src/main/java/org/dromara/dynamictp/core/monitor/collector/MicroMeterCollector.java
> #feature:新增线程池别名用于数据采集

- adapter/adapter-brpc/src/main/java/org/dromara/dynamictp/apapter/brpc/client/StarlightClientDtpAdapter.java
- adapter/adapter-dubbo/src/main/java/org/dromara/dynamictp/adapter/dubbo/apache/ApacheDubboDtpAdapter.java
- common/src/main/java/org/dromara/dynamictp/common/properties/DtpProperties.java
- core/src/main/java/org/dromara/dynamictp/core/refresher/AbstractRefresher.java
- core/src/main/java/org/dromara/dynamictp/core/system/CpuMetricsCaptor.java
- core/src/main/java/org/dromara/dynamictp/core/system/MemoryMetricsCaptor.java
- core/src/main/java/org/dromara/dynamictp/core/system/SystemMetricManager.java
- dependencies/pom.xml
- pom.xml
- starter/starter-common/src/main/resources/META-INF/spring-configuration-metadata.json
> [ISSUE #372] add heap memory usage in alarm message

- core/src/main/java/org/dromara/dynamictp/core/support/ExecutorWrapper.java
#191  refactor：移除getThreadPoolStatProvider方法，使用lombok默认提供的get方法
> refactor：移除getThreadPoolStatProvider方法，使用lombok默认提供的get方法

- core/src/main/java/org/dromara/dynamictp/core/monitor/DtpMonitor.java
[#191 ](https://github.com/dromara/dynamic-tp/issues/191#issuecomment-1899640799)
> perf: 刷新上下文避免重复创建调度任务

- test/test-core/src/test/java/org/dromara/dynamictp/test/core/support/ThreadPoolBuilderTest.java
> add missing Apache License

- core/src/main/java/org/dromara/dynamictp/core/reject/RejectedInvocationHandler.java
> [ISSUE #402] 修复异常拒绝任务时跳过afterReject执行问题

- common/src/main/java/org/dromara/dynamictp/common/constant/LarkNotifyConst.java
- common/src/main/java/org/dromara/dynamictp/common/notifier/LarkNotifier.java
> [ISSUE #410] 修复飞书告警，机器人签名不为空时报错的问题

- common/src/main/java/org/dromara/dynamictp/common/constant/DingNotifyConst.java
- common/src/main/java/org/dromara/dynamictp/common/constant/LarkNotifyConst.java
- common/src/main/java/org/dromara/dynamictp/common/constant/WechatNotifyConst.java
- common/src/main/java/org/dromara/dynamictp/common/entity/NotifyPlatform.java
- common/src/main/java/org/dromara/dynamictp/common/notifier/DingNotifier.java
- common/src/main/java/org/dromara/dynamictp/common/notifier/LarkNotifier.java
- common/src/main/java/org/dromara/dynamictp/common/notifier/WechatNotifier.java
- extension/extension-notify-yunzhijia/src/main/java/org/dromara/dynamictp/extension/notify/yunzhijia/YunZhiJiaNotifier.java
- extension/extension-notify-yunzhijia/src/main/java/org/dromara/dynamictp/extension/notify/yunzhijia/YunZhiJiaNotifyConst.java
- test/test-common/pom.xml
- test/test-common/src/test/java/org/dromara/dynamictp/test/common/notifier/DingNotifierTest.java
- test/test-common/src/test/java/org/dromara/dynamictp/test/common/notifier/LarkNotifierTest.java
- test/test-common/src/test/java/org/dromara/dynamictp/test/common/notifier/WechatNotifierTest.java
- test/test-common/src/test/java/org/dromara/dynamictp/test/common/notifier/YunZhiJiaNotifierTest.java
1. We can copy robot webhook in webhook config
2. Custom webhook should url, not a url with query param(like http://xxx?key=)
3. webhook instead of webHook
> [ISSUE #395] Simplify notifiy Webhook

- adapter/adapter-rocketmq/src/main/java/org/dromara/dynamictp/adapter/rocketmq/RocketMqDtpAdapter.java
> 解决在低版本rocketMQ里没有getAsyncSenderExecutor方法导致NoSuchMethodError

- common/src/main/java/org/dromara/dynamictp/common/entity/MarkdownReq.java
> fix issue 439

- core/src/main/java/org/dromara/dynamictp/core/executor/ScheduledDtpExecutor.java
- core/src/main/java/org/dromara/dynamictp/core/support/ScheduledThreadPoolExecutorProxy.java
> [ISSUE #431] ScheduledDtpExecutor不支持TaskWrapper

- common/src/main/java/org/dromara/dynamictp/common/entity/DtpExecutorProps.java
- common/src/main/java/org/dromara/dynamictp/common/entity/TpExecutorProps.java
- core/src/main/java/org/dromara/dynamictp/core/DtpRegistry.java
- core/src/main/java/org/dromara/dynamictp/core/spring/DtpBeanDefinitionRegistrar.java
- dependencies/pom.xml
- pom.xml
> [ISSUE #472] TpExecutorProps add dtp field for judge if create dtp executor or not

- adapter/adapter-liteflow/pom.xml
- adapter/adapter-liteflow/src/main/java/org/dromara/dynamictp/adapter/liteflow/LiteflowDtpAdapter.java
- adapter/pom.xml
- common/src/main/java/org/dromara/dynamictp/common/properties/DtpProperties.java
- dependencies/pom.xml
- example/example-adapter/example-adapter-liteflow/pom.xml
- example/example-adapter/example-adapter-liteflow/src/main/java/org/dromara/dynamictp/example/LiteflowExampleApplication.java
- example/example-adapter/example-adapter-liteflow/src/main/java/org/dromara/dynamictp/example/cmp/ACmp.java
- example/example-adapter/example-adapter-liteflow/src/main/java/org/dromara/dynamictp/example/cmp/BCmp.java
- example/example-adapter/example-adapter-liteflow/src/main/java/org/dromara/dynamictp/example/cmp/CCmp.java
- example/example-adapter/example-adapter-liteflow/src/main/java/org/dromara/dynamictp/example/controller/TestController.java
- example/example-adapter/example-adapter-liteflow/src/main/java/org/dromara/dynamictp/example/service/BizService.java
- example/example-adapter/example-adapter-liteflow/src/main/resources/application.yml
- example/example-adapter/example-adapter-liteflow/src/main/resources/config/flow.el.xml
- starter/starter-adapter/pom.xml
- starter/starter-adapter/starter-adapter-liteflow/pom.xml
- starter/starter-adapter/starter-adapter-liteflow/src/main/java/org/dromara/dynamictp/starter/adapter/liteflow/autoconfigure/LiteflowTpAutoConfiguration.java
- starter/starter-adapter/starter-adapter-liteflow/src/main/resources/META-INF/spring.factories
> [ISSUE #474] support liteflow threadpool management

- common/src/main/java/org/dromara/dynamictp/common/util/ExecutorUtil.java
> [ISSUE #485] Fix the bug where the scheduled task only runs corePoolSize times

- starter/starter-common/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> perfect additional-spring-configuration-metadata.json

- common/src/main/java/org/dromara/dynamictp/common/em/JreEnum.java
- test/test-common/src/test/java/org/dromara/dynamictp/test/common/em/JreEnumTest.java
> [ISSUE #509] JreEnum lessThan and greaterThan method

- common/src/main/java/org/dromara/dynamictp/common/util/ExecutorUtil.java
- test/test-core/src/test/java/org/dromara/dynamictp/test/core/thread/ScheduledDtpExecutorTest.java
> [ISSUE #515] add scheduledFuture cancel check

- common/src/main/java/org/dromara/dynamictp/common/em/JreEnum.java
- dependencies/pom.xml
- pom.xml
- starter/starter-common/src/main/java/org/dromara/dynamictp/starter/common/monitor/DtpEndpoint.java
> update DtpEndpoint id from dynamic-tp to dynamictp
